<?php
/**
 * Password - A command-line tool to help you manage your password
 *
 * @author  admin@dowte.com
 * @link    https://github.com/dowte/password
 * @license https://opensource.org/licenses/MIT
 */

namespace Dowte\Password\commands;

use Dowte\Password\forms\UserForm;
use Dowte\Password\pass\Password;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Style\SymfonyStyle;
use Stecman\Component\Symfony\Console\BashCompletion\CompletionContext;
use Stecman\Component\Symfony\Console\BashCompletion\Completion\CompletionAwareInterface;

abstract class Command extends \Symfony\Component\Console\Command\Command implements CompletionAwareInterface
{
    const GET_ARGUMENT = 'getArgument';

    const GET_OPTION = 'getOption';

    /**
     * @var SymfonyStyle
     */
    protected $_io;

    /**
     * @var $_input InputInterface
     */
    protected $_input;

    /**
     * @var $_output OutputInterface
     */
    protected $_output;

    public function completeArgumentValues($argumentName, CompletionContext $context)
    {
        return $this->getArgumentValues($argumentName, $context);
    }

    public function completeOptionValues($optionName, CompletionContext $context)
    {
        return $this->getOptionValues($optionName, $context);
    }

    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        $this->_input = $input;
        $this->_output = $output;
        $this->_io = new SymfonyStyle($input, $output);
    }

    /**
     * call a function getOption{{OptionName}}
     *
     * @param $optionName
     * @param CompletionContext $context
     * @return array|mixed
     */
    protected function getOptionValues($optionName, CompletionContext $context)
    {
        $method = self::GET_OPTION . ucfirst($optionName);
        if (method_exists($this, $method)) {
            return call_user_func([$this, $method], $context);
        }
        return [];
    }

    /**
     * call a function getArgument{{ArgumentName}}
     *
     * @param $argumentName
     * @param CompletionContext $context
     * @return array|mixed
     */
    protected function getArgumentValues($argumentName, CompletionContext $context)
    {
        $method = self::GET_ARGUMENT . ucfirst($argumentName);
        if (method_exists($this, $method)) {
            return call_user_func([$this, $method], $context);
        }
        return [];
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }

    /**
     * @return SymfonyStyle
     */
    public function getIO()
    {
        return $this->_io;
    }

    /**
     * return sha256 string from ask
     * @param QuestionHelper $helper
     * @param Question $question
     * @return string
     */
    protected function sha256Ask(QuestionHelper $helper, Question $question)
    {
        $messages = $helper->ask($this->_input, $this->_output, $question);
        return Password::sha256($messages);
    }

    /**
     * @param string $password
     * @param string $user
     * @return array|bool|string
     */
    protected function validPassword($password = '', $user = '')
    {
        if (! $password) {
            $helper = $this->getHelper('question');
            $question = new Question('What is the database master password?');
            $question->setHidden(true);
            $question->setHiddenFallback(false);
            $password = $this->sha256Ask($helper, $question);
        }
        $user = UserForm::user()->findUser($user ?: Password::getUser(), $password);
        if (! $user) {
            Password::error('Please check the master password is right or user is created!');
        } else {
            return $user;
        }
    }
}