<?php

namespace Dowte\Password\base;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SymfonyApplication extends Application
{
    public function run(InputInterface $input = null, OutputInterface $output = null)
    {
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }
}